---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-graalvm
      graalvm_java_version: '17'
      graalvm_version: '21.3.0'

  post_tasks:
    - name: verify graalvm facts
      assert:
        that:
          - ansible_local.graalvm.general.version is defined
          - ansible_local.graalvm.general.java_version is defined
          - ansible_local.graalvm.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
